name: Publish to Docker Hub (on push and scheduled once a week)

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 22 * * 0"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Buildarr v0.6
        uses: docker/build-push-action@v4
        with:
          build-args: |
            BUILDARR_VERSION=0.6.1
            BUILDARR_SONARR_VERSION=0.5.4
            BUILDARR_RADARR_VERSION=0.1.2
            BUILDARR_PROWLARR_VERSION=0.4.2
            BUILDARR_JELLYSEERR_VERSION=0.2.0
          push: true
          tags: |
            callum027/buildarr:0.6.5
            callum027/buildarr:0.6
            callum027/buildarr:latest
