name: Publish to Docker Hub (on push and scheduled once a week)

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 22 * * 0"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/x86_64
          - linux/arm/v7
          - linux/arm/v8
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Buildarr v0.7
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ matrix.platform }}
          build-args: |
            BUILDARR_VERSION=0.7.1
            BUILDARR_SONARR_VERSION=0.6.1
            BUILDARR_RADARR_VERSION=0.2.1
            BUILDARR_PROWLARR_VERSION=0.5.0
            BUILDARR_JELLYSEERR_VERSION=0.3.0
          push: true
          tags: |
            callum027/buildarr:0.7.1
            callum027/buildarr:0.7
            callum027/buildarr:latest
